/*
    Sript para la creación de las tablas del sistema citytrash 
    Bases de datos en mysql 
    TFG SISTEMA CITYTRASH 
    Heidy Mabel Izaguirre Alvarez         
	mvn sql:execute
*/
---------- Table for validation queries from the connection pool. ----------
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";

DROP TABLE IF EXISTS PingTable;
DROP TABLE IF EXISTS TBL_VALORES_REALES;
DROP TABLE IF EXISTS TBL_SENSORES;
DROP TABLE IF EXISTS TBL_RD_CONT;
DROP TABLE IF EXISTS TBL_RD_TP;
DROP TABLE IF EXISTS TBL_RUTAS_DIARIAS;
DROP TABLE IF EXISTS TBL_RU_TP;
DROP TABLE IF EXISTS TBL_CONTENEDORES;
DROP TABLE IF EXISTS TBL_RUTAS;
DROP TABLE IF EXISTS TBL_MODELOS_CONTENEDOR;
DROP TABLE IF EXISTS TBL_CAMIONES;
DROP TABLE IF EXISTS TBL_MC_TB;
DROP TABLE IF EXISTS TBL_MODELOS_CAMION;
DROP TABLE IF EXISTS TBL_TIPOS_BASURA;
DROP TABLE IF EXISTS TBL_TELEFONOS;
DROP TABLE IF EXISTS  TBL_TRABAJADORES;
DROP TABLE IF EXISTS TBL_ALERTAS;

-- pingtable
CREATE TABLE PingTable (foo CHAR(1));


--- ALERTAS
CREATE TABLE TBL_ALERTAS(
ALERTA_ID BIGINT NOT NULL AUTO_INCREMENT,
FECHA_HORA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIORIDAD VARCHAR(20),
TIPO VARCHAR(20),
MENSAJE VARCHAR(250),
RECURSO VARCHAR(250),
CONSTRAINT ALERTA_ID_PK PRIMARY KEY(ALERTA_ID))ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

----------TRABAJADORES----------
CREATE TABLE TBL_TRABAJADORES( 
TRABAJADOR_ID BIGINT NOT NULL AUTO_INCREMENT,
TRABAJADOR_TYPE VARCHAR(20) NOT NULL DEFAULT 'RECOLEC',
ROL VARCHAR(255) NOT NULL,
DOC_ID  VARCHAR(15),
NOMBRE VARCHAR(255) NOT NULL,
APELLIDOS VARCHAR(255) NOT NULL,
FEC_NAC DATE NULL,
EMAIL VARCHAR(100) NOT NULL,
CONTRASENA VARCHAR(60) NULL,
TOKEN VARCHAR(200),
FECHA_EXPIRACION_TOKEN TIMESTAMP NOT NULL,
IDIOMA VARCHAR(3) DEFAULT 'es',
VIA VARCHAR(255),
NUMERO INT,
PISO INT,
PUERTA VARCHAR(50),
PROVINCIA VARCHAR(255),
LOCALIDAD VARCHAR(255),
CP decimal(5,0) UNSIGNED ZEROFILL,
RESTO_DIRECCION VARCHAR(100),
TELEFONO DECIMAL(9,0) UNSIGNED ZEROFILL,
CUENTA_HABILITADA INT DEFAULT 0,
TRABAJADOR_ACTIVO INT DEFAULT 1,
FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FECHA_ACTIVACION TIMESTAMP NULL,
CONSTRAINT TRABAJADORES_ID_PK PRIMARY KEY(TRABAJADOR_ID))
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

		
ALTER TABLE TBL_TRABAJADORES ADD CONSTRAINT TRABAJADORES_EMAIL_UNIQUE UNIQUE (EMAIL);
CREATE INDEX TRABAJADORINDEBYEMAIL_INDEX ON TBL_TRABAJADORES (EMAIL);
ALTER TABLE TBL_TRABAJADORES ADD CONSTRAINT TRABAJADORES_DOC_ID_UNIQUE UNIQUE (DOC_ID);
CREATE INDEX TRABAJADORINDEBYDOC_INDEX ON TBL_TRABAJADORES (DOC_ID);
	


----------TELEFONOS TRABAJADORES----------
CREATE TABLE TBL_TELEFONOS(
TRABAJADOR_ID BIGINT,
TELEFONO CHAR(20) NOT NULL DEFAULT 'HOME',
TIPO VARCHAR(20) NOT NULL,
CONSTRAINT TELEFONO_ID_PK PRIMARY KEY(TRABAJADOR_ID,TELEFONO))
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


ALTER TABLE TBL_TELEFONOS ADD CONSTRAINT TELEFONOS_TRABAJADOR_FK  FOREIGN KEY(TRABAJADOR_ID) REFERENCES TBL_TRABAJADORES (TRABAJADOR_ID);


----------TIPOS DE  BASURA ----------
CREATE TABLE TBL_TIPOS_BASURA(
TIPO_BASURA_ID INT NOT NULL AUTO_INCREMENT,
COLOR VARCHAR(6) UNIQUE,
TIPO VARCHAR(100) NOT NULL UNIQUE,
CONSTRAINT TIPO_BASURA_PK PRIMARY KEY(TIPO_BASURA_ID))
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

----------CAMIONES----------
CREATE TABLE TBL_MODELOS_CAMION(
MODELO_CAMION_ID INT NOT NULL AUTO_INCREMENT,
MODELO VARCHAR(100) NOT NULL UNIQUE,
VOLUMEN_TOLVA DECIMAL(17,2) DEFAULT 0,
ANCHO DECIMAL(17,2) NOT NULL,
ALTURA DECIMAL(17,2) NOT NULL,
LONGITUD DECIMAL(17,2) NOT NULL,
DISTANCIA DECIMAL(17,2) DEFAULT 0,
PMA INT DEFAULT 0,
CONSTRAINT MODELO_CAMION_PK PRIMARY KEY(MODELO_CAMION_ID))
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


ALTER TABLE TBL_MODELOS_CAMION ADD CONSTRAINT MODELO_CAMION_ANCHO_CK CHECK(ANCHO > 0);
ALTER TABLE TBL_MODELOS_CAMION ADD CONSTRAINT MODELO_CAMION_ALTURA_CK CHECK(ALTURA > 0);
ALTER TABLE TBL_MODELOS_CAMION ADD CONSTRAINT MODELO_CAMION_LONGITUD_CK CHECK(LONGITUD > 0);


-- MODELO CAMION TIPO DE BASURA
CREATE TABLE TBL_MC_TB(
MODELO_CAMION INT NOT NULL,
TIPO_BASURA  INT NOT NULL,
CAPACIDAD DECIMAL(17,2) NOT NULL,
CONSTRAINT MODELOCAMION_TIPOBASURAPK PRIMARY KEY(MODELO_CAMION,TIPO_BASURA))
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


ALTER TABLE TBL_MC_TB ADD CONSTRAINT TBL_MODELOCAMION_TIPOBASURA_MODELO_FK FOREIGN KEY(MODELO_CAMION) REFERENCES TBL_MODELOS_CAMION (MODELO_CAMION_ID);
ALTER TABLE TBL_MC_TB ADD CONSTRAINT TBL_MODELOCAMION_TIPOBASURA_TIPO_FK FOREIGN KEY(TIPO_BASURA) REFERENCES TBL_TIPOS_BASURA (TIPO_BASURA_ID);
ALTER TABLE TBL_MC_TB ADD CONSTRAINT TBL_CAPACIDAD_CHECK CHECK(CAPACIDAD > 0);

--- CAMIONES
CREATE TABLE TBL_CAMIONES(
CAMION_ID BIGINT NOT NULL AUTO_INCREMENT,
VIN VARCHAR(17) UNIQUE,
NOMBRE VARCHAR(50) UNIQUE NOT NULL,
MATRICULA VARCHAR(20) UNIQUE NULL,
FECHA_ALTA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
FECHA_BAJA TIMESTAMP NULL,
MODELO_CAMION INT NOT NULL,
RECOGEDOR_ASIGNADO1 BIGINT,
RECOGEDOR_ASIGNADO2 BIGINT,
CODUCTOR_ASIGNADO BIGINT,
CONDUCTOR_SUPLENTE BIGINT,
ACTIVO BIT DEFAULT 1,
CONSTRAINT CAMIONES_PK PRIMARY KEY(CAMION_ID))
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE TBL_CAMIONES ADD CONSTRAINT CAMIONES_MODELO_FK FOREIGN KEY(MODELO_CAMION) REFERENCES TBL_MODELOS_CAMION (MODELO_CAMION_ID);
ALTER TABLE TBL_CAMIONES ADD CONSTRAINT CAMIONES_RECOGEDOR1_FK FOREIGN KEY(RECOGEDOR_ASIGNADO1) REFERENCES TBL_TRABAJADORES (TRABAJADOR_ID);
ALTER TABLE TBL_CAMIONES ADD CONSTRAINT CAMIONES_RECOGEDOR2_FK FOREIGN KEY(RECOGEDOR_ASIGNADO2) REFERENCES TBL_TRABAJADORES (TRABAJADOR_ID);
ALTER TABLE TBL_CAMIONES ADD CONSTRAINT CAMIONES_CONDUCTOR_ASIGNADO_FK FOREIGN KEY(CODUCTOR_ASIGNADO) REFERENCES TBL_TRABAJADORES (TRABAJADOR_ID);
ALTER TABLE TBL_CAMIONES ADD CONSTRAINT CAMIONES_CONDUCTOR_SUPLENTE_FK FOREIGN KEY(CONDUCTOR_SUPLENTE) REFERENCES TBL_TRABAJADORES (TRABAJADOR_ID);

---------- CONTENEDORES ------------
CREATE TABLE TBL_MODELOS_CONTENEDOR(
MODELO_CONTENEDOR_ID INT NOT NULL AUTO_INCREMENT,
NOMBRE VARCHAR(100) NOT NULL UNIQUE,
CAPACIDAD_NOMINAL DECIMAL(17,2) NOT NULL,
CARGA_NOMINAL DECIMAL(17,2) NOT NULL,
PROFUNDIDAD DECIMAL(17,2),
ALTURA DECIMAL(17,2),
ANCHURA DECIMAL(17,2),
PESO_VACIO DECIMAL(17,2),
TIPO_BASURA  INT,
CONSTRAINT MODELOS_CONTENEDOR_PK PRIMARY KEY(MODELO_CONTENEDOR_ID))
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE TBL_MODELOS_CONTENEDOR ADD CONSTRAINT MODELOS_CONTENEDOR_CARGA_NOMINAL_CK CHECK(CARGA_NOMINAL > 0);
ALTER TABLE TBL_MODELOS_CONTENEDOR ADD CONSTRAINT MODELOS_CONTENEDOR_CAMPACIDAD_NOMINAL_CK CHECK(CAPACIDAD_NOMINAL > 0);
ALTER TABLE TBL_MODELOS_CONTENEDOR ADD CONSTRAINT MODELOS_CONTENEDOR_TIPOBASURA_FK FOREIGN KEY(TIPO_BASURA) REFERENCES TBL_TIPOS_BASURA (TIPO_BASURA_ID);

---------- RUTAS ------------
CREATE TABLE TBL_RUTAS(
RUTA_ID INT NOT NULL AUTO_INCREMENT,
INICIO_LATITUD DOUBLE,
INICIO_LONGITUD DOUBLE,
FIN_LATITUD DOUBLE,
FIN_LONGITUD DOUBLE,
ACTIVO BIT DEFAULT 1,
CAMION_ID BIGINT,
CONSTRAINT RUTA_PK PRIMARY KEY(RUTA_ID))
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE TBL_RUTAS ADD CONSTRAINT RUTAS_CAMION_FK FOREIGN KEY(CAMION_ID) REFERENCES TBL_CAMIONES (CAMION_ID);

--CONTENEDORES
CREATE TABLE TBL_CONTENEDORES(
CONTENEDOR_ID BIGINT NOT NULL AUTO_INCREMENT,
NOMBRE VARCHAR(100) NOT NULL UNIQUE,
LOCALIZACION_LATITUD DOUBLE,
LOCALIZACION_LONGITUD DOUBLE,
FECHA_ALTA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
FECHA_BAJA TIMESTAMP NULL,
ACTIVO BIT DEFAULT 1,
MODELO_CONTENEDOR INT NOT NULL,
RUTA_ID INT,
CONSTRAINT CONTENEDOR_PK PRIMARY KEY(CONTENEDOR_ID))
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE TBL_CONTENEDORES ADD CONSTRAINT CONTENEDOR_MODELO_FK FOREIGN KEY(MODELO_CONTENEDOR) REFERENCES TBL_MODELOS_CONTENEDOR (MODELO_CONTENEDOR_ID);
ALTER TABLE TBL_CONTENEDORES ADD CONSTRAINT CONTENEDOR_RUTA_FK FOREIGN KEY(RUTA_ID) REFERENCES TBL_RUTAS (RUTA_ID);

-- RUTAS DIARIAS TIPOS DE BASURA
CREATE TABLE TBL_RU_TP(
TIPO_BASURA INT NOT NULL,
RUTA_ID INT NOT NULL,
CONSTRAINT RU_TP_PK PRIMARY KEY(TIPO_BASURA,RUTA_ID))
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE TBL_RU_TP ADD CONSTRAINT RU_TP_TIPOBASURA_FK FOREIGN KEY(TIPO_BASURA) REFERENCES TBL_TIPOS_BASURA (TIPO_BASURA_ID);
ALTER TABLE TBL_RU_TP ADD CONSTRAINT RU_TP_RUTA_FK FOREIGN KEY(RUTA_ID) REFERENCES TBL_RUTAS (RUTA_ID);


-- HISTORIAL DE RUTAS
CREATE TABLE TBL_RUTAS_DIARIAS(
RUTA_DIARIA_ID BIGINT NOT NULL AUTO_INCREMENT,
FECHA DATE NOT NULL,
RUTA_ID INT NOT NULL,
FECHA_HORA_INICIO TIMESTAMP NULL,
FECHA_HORA_FIN TIMESTAMP NULL,
RECOGEDOR1 BIGINT,
RECOGEDOR2 BIGINT,
CONDUCTOR_ASIGNADO BIGINT,
TRABAJADOR_ACTUALIZA BIGINT,
FECHA_HORA_ACTUALIZACION TIMESTAMP NULL,
CAMION_ID INT,
CONSTRAINT chk_fechaFin CHECK (FECHA_HORA_FIN > FECHA_HORA_INICIO),
CONSTRAINT RUTAS_DIARIAS_PK PRIMARY KEY(RUTA_DIARIA_ID))
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE TBL_RUTAS_DIARIAS ADD CONSTRAINT RUTAS_DIARIAS_RUTA_FK FOREIGN KEY(RUTA_ID) REFERENCES TBL_RUTAS (RUTA_ID);
ALTER TABLE TBL_RUTAS_DIARIAS ADD CONSTRAINT RUTAS_DIARIAS_RECOGEDOR2_FK FOREIGN KEY(RECOGEDOR1) REFERENCES TBL_TRABAJADORES (TRABAJADOR_ID);
ALTER TABLE TBL_RUTAS_DIARIAS ADD CONSTRAINT RUTAS_DIARIAS_RECOGEDOR1_FK FOREIGN KEY(RECOGEDOR2) REFERENCES TBL_TRABAJADORES (TRABAJADOR_ID);
ALTER TABLE TBL_RUTAS_DIARIAS ADD CONSTRAINT RUTAS_DIARIAS_CONDUCTOR_FK FOREIGN KEY(CONDUCTOR_ASIGNADO) REFERENCES TBL_TRABAJADORES (TRABAJADOR_ID);
ALTER TABLE TBL_RUTAS_DIARIAS ADD CONSTRAINT RUTAS_DIARIAS_TRABAJADORACTUAL_FK FOREIGN KEY(TRABAJADOR_ACTUALIZA) REFERENCES TBL_TRABAJADORES (TRABAJADOR_ID);


--TIPOS DE BASURA DE LAS RUTAS DIARIAS
CREATE TABLE TBL_RD_TP(
TIPO_BASURA_ID INT NOT NULL,
RUTA_DIARIA_ID BIGINT NOT NULL,
CONSTRAINT RU_TP_PK PRIMARY KEY(TIPO_BASURA_ID,RUTA_DIARIA_ID))
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE TBL_RD_TP ADD CONSTRAINT TBL_RD_TP_TB_FK FOREIGN KEY(TIPO_BASURA_ID) REFERENCES TBL_TIPOS_BASURA (TIPO_BASURA_ID);
ALTER TABLE TBL_RD_TP ADD CONSTRAINT TBL_RD_TP_RD_FK FOREIGN KEY(RUTA_DIARIA_ID) REFERENCES TBL_RUTAS_DIARIAS (RUTA_DIARIA_ID);

-- RUTAS DIARIAS CONTENEDORES ASIGNADOS 
CREATE TABLE TBL_RD_CONT(
RUTA_DIARIA_ID BIGINT NOT NULL,
CONTENEDOR_ID BIGINT NOT NULL,
SUGERENCIA BIT NOT NULL DEFAULT 1,
REGOGIO BIT NOT NULL DEFAULT 0,
FECHA_HORA TIMESTAMP NULL,
TRABAJADOR_ACTUALIZA BIGINT)
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE TBL_RD_CONT ADD CONSTRAINT RD_CONT_PK PRIMARY KEY(RUTA_DIARIA_ID,CONTENEDOR_ID);
ALTER TABLE TBL_RD_CONT ADD CONSTRAINT RD_CONT_RUTA_RUTA_FK FOREIGN KEY(RUTA_DIARIA_ID) REFERENCES TBL_RUTAS_DIARIAS (RUTA_DIARIA_ID) ON DELETE CASCADE;
ALTER TABLE TBL_RD_CONT ADD CONSTRAINT RD_CONT_RUTA_CONTENEDOR_FK FOREIGN KEY(CONTENEDOR_ID) REFERENCES TBL_CONTENEDORES (CONTENEDOR_ID);
ALTER TABLE TBL_RD_CONT ADD CONSTRAINT RD_CONT_RUTA_TRABAJADORACTUAL_FK FOREIGN KEY(TRABAJADOR_ACTUALIZA) REFERENCES TBL_TRABAJADORES (TRABAJADOR_ID);

--SENSORES

CREATE TABLE TBL_SENSORES(
SENSOR_ID BIGINT NOT NULL AUTO_INCREMENT,
NOMBRE VARCHAR(100) NOT NULL,
CONTENEDOR BIGINT NOT NULL,
ACTIVO BIT NOT NULL DEFAULT 1,
ULTIMA_ACTUALIZACION TIMESTAMP NULL, 
SENSOR_TIPO VARCHAR(30) NOT NULL,
BT_PORCENTAJE DOUBLE DEFAULT 0,
TE_CENTIGRADOS DOUBLE DEFAULT 0,
VO_PORCENTAJE DOUBLE DEFAULT 0,
CONSTRAINT SENSORES_PK PRIMARY KEY(SENSOR_ID))
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


--ALTER TABLE TBL_SENSORES ADD CONSTRAINT SENSORES_CONTENEDOR_FK FOREIGN KEY(CONTENEDOR) REFERENCES TBL_CONTENEDORES (CONTENEDOR_ID);

ALTER TABLE TBL_SENSORES ADD CONSTRAINT SENSORES_CONTENEDOR_FK_ FOREIGN KEY(CONTENEDOR) REFERENCES 
TBL_CONTENEDORES (CONTENEDOR_ID) ON UPDATE CASCADE; 

--VALORES SENSORES
CREATE TABLE TBL_VALORES_REALES(
FECHA_HORA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
SENSOR_ID BIGINT NOT NULL,
VALOR DOUBLE,
CONSTRAINT VALORES_REALES_PK PRIMARY KEY(SENSOR_ID,FECHA_HORA))
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE TBL_VALORES_REALES ADD CONSTRAINT VALORES_REALES_SENSORES_FK 
FOREIGN KEY(SENSOR_ID) REFERENCES TBL_SENSORES (SENSOR_ID) ON DELETE CASCADE;

