
-- INSERT A DEFAULT USER => TIENE PARA ACTIVAR LA CUENTA UN DÍA con el siguiente enlace:
--citytrashAdmi123 => contraseñas gmail y la cuenta de cityTrash
--citytrashaRecol123 => contraseñas gmail y la cuenta de citYtRASH
-- http://localhost:8080/citytrash/cuenta/activar?id=1&token=347 
--http://localhost:8080/citytrash/cuenta/activar?id=2&token=169


INSERT INTO TBL_TRABAJADORES(TRABAJADOR_TYPE, ROL, DOC_ID, NOMBRE, APELLIDOS, EMAIL,VIA,NUMERO,PISO,PUERTA,RESTO_DIRECCION,CP,LOCALIDAD, PROVINCIA,TOKEN, FECHA_EXPIRACION_TOKEN) VALUES 
('ADMIN','ROLE_ADMIN','12355678J','Selenium','ADMINISTRADOR','citytrashadmi@gmail.com','CALLE LUIS JORGE CASTAÑOS', 23,4,'Dcha','URBANIZACIÓN LAS CASCAJUELAS',28999,'VALDECILLAS DE JARAMA', 'madrid', '347', DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 24 HOUR)),
('RECOLEC','ROLE_USER','Y1235567K','Selenium','RECOLECTOR','citytrasharecol@gmail.com', 'C JUANA DE VEGA', 10,6,'A',null,15004,'A CORUÑA', 'A CORUÑA','169', DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 24 HOUR));

--http://localhost:8080/citytrash/cuenta/activar?id=2&token=169
--INSERT INTO TBL_TRABAJADORES(TRABAJADOR_TYPE, ROL, DOC_ID, NOMBRE, APELLIDOS, EMAIL,VIA,NUMERO,PISO,PUERTA,RESTO_DIRECCION,CP,LOCALIDAD, PROVINCIA,TOKEN, FECHA_EXPIRACION_TOKEN) VALUES 
--('RECOLEC','ROLE_USER','Y1235567K','Selenium','RECOLECTOR','citytrasharecol@gmail.com', 'C JUANA DE VEGA', 10,6,'A',null,15004,'A CORUÑA', 'A CORUÑA','169', DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 24 HOUR));
-- UPDATE TBL_TRABAJADORES SET TRABAJADOR_ID = 2 WHERE TRABAJADOR_ID = 3;

