
-- INSERT A DEFAULT USER => TIENE PARA ACTIVAR LA CUENTA UN DÍA con el siguiente enlace:
-- http://localhost:8080/citytrash/cuenta/activar?id=1&token=6a3bee2d-0e08-4f00-9aff-30d9338d58fa&lang=es 


INSERT INTO TBL_TRABAJADORES(TRABAJADOR_TYPE, ROL, DOC_ID, NOMBRE, APELLIDOS, EMAIL, TOKEN, FECHA_EXPIRACION_TOKEN) 
VALUES ('ADMINISTRADOR','ROLE_ADMIN','XXXXXXXX','ADMINISTRADOR','DEFAULT','citytrashtfg@gmail.com', '6a3bee2d-0e08-4f00-9aff-30d9338d58fa', DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 24 HOUR));



